name: whattodo_final
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  carousel_slider: ^4.2.1
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_slidable: ^3.0.0
  google_fonts: ^4.0.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^1.1.3
  build_runner: ^2.1.11
  
flutter_icons: 
  android: "launcher_icon"
  ios: true
  image_path: "lib/assets/icons/icon.png"

flutter:
  uses-material-design: true
  assets:
    - lib/assets/
    - lib/assets/appbar-bg.png
  fonts:
  - family: Playpen Sans
    fonts:
    - asset: lib/assets/fonts/PlaypenSans-Regular.ttf
    - asset: lib/assets/fonts/PlaypenSans-Bold.ttf
      
