name: whattodo_final
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  carousel_slider: ^4.2.1
  flutter:
    sdk: flutter
carousel_slider: ^4.2.1 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/todo-image.png
    - lib/assets/todo-2.png
    - lib/assets/todo-3.png
